create sequence hibernate_sequence start 1 increment 1;

create table images (
id int8 generated by default as identity,
bytes oid,
content_type varchar(255),
name varchar(255),
original_file_name varchar(255),
preview_image boolean not null,
size int8,
product_id int8,
primary key (id)
);

create table prod (
id int8 not null,
city varchar(255),
date_created timestamp,
description varchar(255),
preview_image_id int8,
price int4 not null,
title varchar(255),
user_id int8,
primary key (id)
);

create table usr (
id int8 generated by default as identity,
activation_code varchar(255),
active boolean not null,
date_time timestamp,
email varchar(255) not null,
name varchar(255) not null,
password varchar(100) not null,
image_id int8,
primary key (id)
);

create table usr_role (
usr_id int8 not null,
roles varchar(255)
);

alter table if exists usr
add constraint UK_g9l96r670qkidthshajdtxrqf unique (email);

alter table if exists images
add constraint FK3vub38p55r7ej444yixv7e31b
foreign key (product_id) references prod;

alter table if exists prod
add constraint FKtg30g3hy8hnfl53tl522yup79
foreign key (user_id) references usr;

alter table if exists usr
add constraint FKbcmy2jxq268wxp06utcg1uvoo
foreign key (image_id) references images;

alter table if exists usr_role
add constraint FK9ffk6ts9njcytrt8ft17fvr3p
foreign key (usr_id) references usr;